# Generated by Django 3.2.6 on 2021-08-27 12:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100, verbose_name='Улица, проспект, шоссе, переулок')),
                ('house', models.CharField(max_length=100, verbose_name='Дом')),
                ('block', models.CharField(max_length=100, null=True, verbose_name='Корпус')),
                ('building', models.CharField(max_length=100, null=True, verbose_name='Строение')),
                ('place', models.CharField(max_length=100, null=True, verbose_name='Офис/Квартира')),
                ('postcode', models.CharField(max_length=6, verbose_name='Индекс')),
                ('subject', models.IntegerField(choices=[(1, 'Республика Адыгея (Адыгея)'), (2, 'Республика Башкортостан'), (3, 'Республика Бурятия'), (4, 'Республика Алтай'), (5, 'Республика Дагестан'), (6, 'Республика Ингушетия'), (7, 'Кабардино-Балкарская Республика'), (8, 'Республика Калмыкия'), (9, 'Карачаево-Черкесская Республика'), (10, 'Республика Карелия'), (11, 'Республика Коми'), (12, 'Республика Марий Эл'), (13, 'Республика Мордовия'), (14, 'Республика Саха (Якутия)'), (15, 'Республика Северная Осетия - Алания'), (16, 'Республика Татарстан (Татарстан)'), (17, 'Республика Тыва'), (18, 'Удмуртская Республика'), (19, 'Республика Хакасия'), (20, 'Чеченская Республика'), (21, 'Чувашская Республика - Чувашия'), (22, 'Алтайский край'), (23, 'Краснодарский край'), (24, 'Красноярский край'), (25, 'Приморский край'), (26, 'Ставропольский край'), (27, 'Хабаровский край'), (28, 'Амурская область'), (29, 'Архангельская область'), (30, 'Астраханская область'), (31, 'Белгородская область'), (32, 'Брянская область'), (33, 'Владимирская область'), (34, 'Волгоградская область'), (35, 'Вологодская область'), (36, 'Воронежская область'), (37, 'Ивановская область'), (38, 'Иркутская область'), (39, 'Калининградская область'), (40, 'Калужская область'), (41, 'Камчатский край'), (42, 'Кемеровская область'), (43, 'Кировская область'), (44, 'Костромская область'), (45, 'Курганская область'), (46, 'Курская область'), (47, 'Ленинградская область'), (48, 'Липецкая область'), (49, 'Магаданская область'), (50, 'Московская область'), (51, 'Мурманская область'), (52, 'Нижегородская область'), (53, 'Новгородская область'), (54, 'Новосибирская область'), (55, 'Омская область'), (56, 'Оренбургская область'), (57, 'Орловская область'), (58, 'Пензенская область'), (59, 'Пермский край'), (60, 'Псковская область'), (61, 'Ростовская область'), (62, 'Рязанская область'), (63, 'Самарская область'), (64, 'Саратовская область'), (65, 'Сахалинская область'), (66, 'Свердловская область'), (67, 'Смоленская область'), (68, 'Тамбовская область'), (69, 'Тверская область'), (70, 'Томская область'), (71, 'Тульская область'), (72, 'Тюменская область'), (73, 'Ульяновская область'), (74, 'Челябинская область'), (75, 'Забайкальский край'), (76, 'Ярославская область'), (77, 'Москва'), (78, 'Санкт-Петербург'), (79, 'Еврейская автономная область'), (83, 'Ненецкий автономный округ'), (86, 'Ханты-Мансийский Автономный округ - Югра'), (87, 'Чукотский автономный округ'), (89, 'Ямало-Ненецкий автономный округ'), (91, 'Республика Крым'), (92, 'Севастополь'), (99, 'Иные территории, включая город и космодром Байконур')], verbose_name='Субъект РФ')),
                ('type', models.CharField(choices=[('аал', 'аал'), ('аул', 'аул'), ('волость', 'волость'), ('высел', 'выселки(ок)'), ('г', 'город'), ('городок', 'городок'), ('д', 'деревня'), ('дп', 'дачный поселок'), ('ж/д_будка', 'железнодорожная будка'), ('ж/д_казарм', 'железнодорожная казарма'), ('ж/д_оп', 'ж/д остановочный (обгонный) пункт'), ('ж/д_платф', 'железнодорожная платформа'), ('ж/д_пост', 'железнодорожный пост'), ('ж/д_рзд', 'железнодорожный разъезд'), ('ж/д_ст', 'железнодорожная станция'), ('заимка', 'заимка'), ('казарма', 'казарма'), ('кп', 'курортный поселок'), ('м', 'местечко'), ('мкр', 'микрорайон'), ('нп', 'населенный пункт'), ('остров', 'остров'), ('п', 'поселок сельского типа'), ('п/о', 'почтовое отделение'), ('п/р', 'планировочный район'), ('п/ст', 'поселок и(при) станция(и)'), ('пгт', 'поселок городского типа'), ('починок', 'починок'), ('промзона', 'промышленная зона'), ('рзд', 'разъезд'), ('рп', 'рабочий (заводской) поселок'), ('с', 'село'), ('с/а', 'сельская администрация'), ('с/мо', 'сельское муницип. образование'), ('с/о', 'сельский округ'), ('с/пос', 'сельское поселение'), ('с/с', 'сельсовет'), ('с/тер', 'сельская территория'), ('сл', 'слобода'), ('ст-ца', 'станица'), ('тер', 'территория'), ('у', 'улус'), ('х', 'хутор')], max_length=10, verbose_name='Тип населенного пункта')),
                ('locality', models.CharField(max_length=100, verbose_name='Название населенного пункта')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование торговой точки')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('blocked', 'Заблокирован'), ('removed', 'Удалён')], default='active', max_length=7, verbose_name='Статус')),
                ('telegram_id', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Идентификатор торговой точки в боте')),
            ],
            options={
                'verbose_name': 'Торговая точка',
                'verbose_name_plural': 'Торговые точки',
            },
        ),
        migrations.CreateModel(
            name='OutletAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Связь торговой точки с агентом',
                'verbose_name_plural': 'Связи торговых точек с агентами',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('legal_name', models.CharField(max_length=250, verbose_name='Официальное наименовение')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('TIN', models.CharField(max_length=12, verbose_name='ИНН')),
                ('PSRN', models.CharField(max_length=15, verbose_name='ОГРН')),
                ('IEC', models.CharField(max_length=9, verbose_name='КПП')),
                ('CA', models.CharField(max_length=20, verbose_name='Корреспондентский счёт')),
                ('giro', models.CharField(max_length=20, verbose_name='Расчётный счёт')),
                ('RCBIC', models.CharField(max_length=9, verbose_name='БИК')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='PartnerBank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Связь партнёра и банка',
                'verbose_name_plural': 'Связи партнёров и банков',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
    ]
