# Generated by Django 3.2.6 on 2021-08-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('banks', '0002_initial'),
        ('misc', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='acc_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_regions', to='users.accman'),
        ),
        migrations.AddField(
            model_name='partnerbank',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner_banks', to='banks.bank'),
        ),
        migrations.AddField(
            model_name='partnerbank',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner_banks', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='partner',
            name='actual_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.location', verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='partner',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='misc.mesabank'),
        ),
        migrations.AddField(
            model_name='partner',
            name='legal_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.location', verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='partner',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='partners.region'),
        ),
        migrations.AddField(
            model_name='partner',
            name='ter_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='users.terman'),
        ),
        migrations.AddField(
            model_name='outletagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_agents', to='users.agent'),
        ),
        migrations.AddField(
            model_name='outletagent',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_agents', to='partners.outlet'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.location'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='agents',
            field=models.ManyToManyField(related_name='outlets', through='partners.OutletAgent', to='users.Agent'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='banks',
            field=models.ManyToManyField(related_name='outlets', through='banks.OutletBank', to='banks.Bank'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='partners.partner'),
        ),
        migrations.AlterUniqueTogether(
            name='outletagent',
            unique_together={('agent', 'outlet')},
        ),
    ]
