# Generated by Django 3.2.6 on 2021-12-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='IEC',
            field=models.CharField(max_length=9, null=True, verbose_name='КПП'),
        ),
    ]
