# Generated by Django 3.2.6 on 2021-08-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('banks', '0002_initial'),
        ('orders', '0001_initial'),
        ('misc', '0001_initial'),
        ('partners', '0001_initial'),
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramorder',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='partners.outlet', verbose_name='Торговая точка'),
        ),
        migrations.AddField(
            model_name='personaldatatemptoken',
            name='personal_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.personaldata'),
        ),
        migrations.AddField(
            model_name='personaldatafile',
            name='personal_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.personaldata'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='appearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='misc.newaccordance', verbose_name='Внешний вид клиента'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_data', to='orders.client'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='habitation_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.location'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to='orders.order'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='registry_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.location', verbose_name='Место регистрации'),
        ),
        migrations.AddField(
            model_name='passport',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='passport', to='orders.client'),
        ),
        migrations.AddField(
            model_name='passport',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordertemptoken',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='credit_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.ordercreditproduct'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordergoodservice',
            name='order_good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_services', to='orders.ordergood'),
        ),
        migrations.AddField(
            model_name='ordergoodservice',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='misc.newaccordance', verbose_name='Дополнительная услуга к товару'),
        ),
        migrations.AddField(
            model_name='ordergood',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_goods', to='orders.good'),
        ),
        migrations.AddField(
            model_name='ordergood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderextraservice',
            name='extra_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_extra_services', to='banks.extraservice'),
        ),
        migrations.AddField(
            model_name='orderextraservice',
            name='order_credit_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_extra_services', to='orders.ordercreditproduct'),
        ),
        migrations.AddField(
            model_name='ordercreditproduct',
            name='credit_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_credit_products', to='banks.creditproduct'),
        ),
        migrations.AddField(
            model_name='ordercreditproduct',
            name='extra_services',
            field=models.ManyToManyField(through='orders.OrderExtraService', to='banks.ExtraService'),
        ),
        migrations.AddField(
            model_name='ordercreditproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_credit_products', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='users.agent'),
        ),
        migrations.AddField(
            model_name='order',
            name='chosen_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_chosen', to='orders.ordercreditproduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='orders.clientorder'),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_products',
            field=models.ManyToManyField(related_name='orders_pre', through='orders.OrderCreditProduct', to='banks.CreditProduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='partners.outlet'),
        ),
        migrations.AddField(
            model_name='order',
            name='telegram_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.telegramorder'),
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='misc.newaccordance', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='familydata',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='family_data', to='orders.client'),
        ),
        migrations.AddField(
            model_name='familydata',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_data', to='orders.order'),
        ),
        migrations.AddField(
            model_name='familydata',
            name='partner_position_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='misc.newaccordance', verbose_name='Тип должности'),
        ),
        migrations.AddField(
            model_name='extradata',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='extra_datas', to='orders.client'),
        ),
        migrations.AddField(
            model_name='extradata',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_data', to='orders.order'),
        ),
        migrations.AddField(
            model_name='documenttosign',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_to_sign', to='orders.order'),
        ),
        migrations.AddField(
            model_name='documentsigned',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_signed', to='orders.order'),
        ),
        migrations.AddField(
            model_name='credit',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='credits', to='orders.client'),
        ),
        migrations.AddField(
            model_name='credit',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='orders.order'),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='deliveries.delivery'),
        ),
        migrations.AddField(
            model_name='contract',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='orders.order'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='orders.client'),
        ),
        migrations.AddField(
            model_name='careereducation',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='career_education', to='orders.client'),
        ),
        migrations.AddField(
            model_name='careereducation',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_education', to='orders.order'),
        ),
        migrations.AddField(
            model_name='careereducation',
            name='org_industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='misc.newaccordance', verbose_name='Вид деятельности организации'),
        ),
        migrations.AddField(
            model_name='careereducation',
            name='org_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partners.location'),
        ),
        migrations.AddField(
            model_name='careereducation',
            name='org_ownership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='misc.newaccordance', verbose_name='Форма собственности организации'),
        ),
        migrations.AddField(
            model_name='careereducation',
            name='position_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='misc.newaccordance', verbose_name='Тип должности'),
        ),
    ]
