# Generated by Django 3.2.6 on 2021-08-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='work_loss_insurance_code',
            field=models.PositiveSmallIntegerField(choices=[(1, '2-927ER1Q ОАО "АльфаСтрахование"'), (2, '2-927EQYN ОАО "АльфаСтрахование"'), (3, '2-5E9TTXC ОАО "Военно-страховая компания"'), (4, '2-A62U1CG ОАО "АльфаСтрахование"')], null=True),
        ),
    ]
