<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://siebel.com/CustomUI"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsdLocal1="http://www.siebel.com/xml/ATC%20Broker%20Opportunity%20Status"
	xmlns:xsdLocal2="http://www.siebel.com/xml/ApplicationInfoMQ"
	name="BrokerOpportunityStatus"
	targetNamespace="http://siebel.com/CustomUI">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import
				namespace="http://www.siebel.com/xml/ATC%20Broker%20Opportunity%20Status"
				schemaLocation="BrokerOpportunityStatusRequest.xsd">
			</xsd:import>
			<xsd:import
				namespace="http://www.siebel.com/xml/ApplicationInfoMQ"
				schemaLocation="ApplicationInfoMQ.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="BrokerOpportunityStatus_Input">
		<wsdl:part
			element="xsdLocal1:ListOfAtcBrokerOpportunityStatus"
			name="BrokerOpportunityStatus_Input" />
	</wsdl:message>
	<wsdl:message name="BrokerOpportunityStatus_Output">
		<wsdl:part element="xsdLocal2:ApplicationInfoMQ"
			name="BrokerOpportunityStatus_Output" />
	</wsdl:message>

	<wsdl:portType name="BrokerOpportunityStatus">
		<wsdl:operation name="BrokerOpportunityStatus">
			<wsdl:input message="tns:BrokerOpportunityStatus_Input" />
			<wsdl:output message="tns:BrokerOpportunityStatus_Output" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="BrokerOpportunityStatusSOAP"
		type="tns:BrokerOpportunityStatus">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="BrokerOpportunityStatus">
			<soap:operation
				soapAction="http://siebel.com/CustomUI/BrokerOpportunityStatus" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="BrokerOpportunityStatus">
		<wsdl:port binding="tns:BrokerOpportunityStatusSOAP"
			name="BrokerOpportunityStatusSOAP">
			<soap:address location="http://172.18.18.20/" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
