version: '3.7'
services:
  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.21
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/STATIC
    ports:
      - 80:80
    depends_on:
      - web
  web:
    container_name: dev_backend
    build: .
    restart: always
    command: gunicorn serv_finance.wsgi:application --bind 0.0.0.0:8000
#    command: python3 manage.py runserver
    volumes:
     - .:/app
     - static_volume:/app/STATIC
    depends_on:
     - db
  db:
    container_name: dev_db
    image: postgres:13.3
    env_file: docker-db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_volume:
  postgres_data:
