# Generated by Django 3.2.6 on 2021-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MesaBank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='NewAccordance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100)),
                ('general', models.CharField(max_length=100, unique=True)),
                ('specific', models.JSONField()),
                ('collection', models.CharField(choices=[('industry', 'Индустрия организации клиента банка'), ('appearance', 'Внешний вид клиента'), ('good_category', 'Категория товара'), ('good_service', 'Программы услуг для товара'), ('position_type', 'Тип должности клиента'), ('org_ownership', 'Форма собственности организации')], db_index=True, max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='mesabank',
            index=models.Index(fields=['name'], name='misc_mesaba_name_fe3fab_idx'),
        ),
    ]
