# Generated by Django 3.2.6 on 2021-08-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('code', models.CharField(blank=True, max_length=150, null=True, verbose_name='Код агента в банке')),
            ],
            options={
                'verbose_name': 'Связь агента с банком',
                'verbose_name_plural': 'Связи агентов с банками',
            },
        ),
        migrations.CreateModel(
            name='AgentCreditProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Комиссия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступность')),
            ],
            options={
                'verbose_name': 'Настройки кредитного продукта для агента',
                'verbose_name_plural': 'Настройки кредитных продуктов для агента',
            },
        ),
        migrations.CreateModel(
            name='AgentExtraService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Комиссия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступность')),
            ],
            options={
                'verbose_name': 'Настройки доп. услуги для агента',
                'verbose_name_plural': 'Настройки доп. услуг для агента',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('OTP', 'OTП Банк'), ('ALFA', 'Альфа Банк'), ('POCHTA', 'Почта Банк'), ('MTS', 'МТС Банк')], max_length=6, unique=True)),
                ('logo', models.FileField(max_length=1000, upload_to='')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='CreditProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('total_min', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма. От')),
                ('total_max', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма. До')),
                ('term_min', models.PositiveSmallIntegerField(verbose_name='Срок. От')),
                ('term_max', models.PositiveSmallIntegerField(verbose_name='Срок. До')),
                ('initial_payment_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Первоначальный взнос. От')),
                ('initial_payment_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Первоначальный взнос. До')),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Годовой процент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен')),
                ('code', models.CharField(max_length=200, null=True, verbose_name='Код в банке')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('basic', 'Основная услуга'), ('custom', 'Другое')], default='custom', max_length=6, verbose_name='Тип доп. услуги')),
                ('price_type', models.CharField(choices=[('percent', 'Процент от суммы кредита'), ('currency', 'Твёрдая сумма')], default='percent', max_length=8, verbose_name='Тип цены')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutletBank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Связь торговой точки и банка',
                'verbose_name_plural': 'Связи торговых точек и банков',
            },
        ),
        migrations.CreateModel(
            name='OutletCreditProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступность')),
            ],
            options={
                'verbose_name': 'Настройки кредитного продукта для торговой точки',
                'verbose_name_plural': 'Настройки кредитных продуктов для торговых точек',
            },
        ),
        migrations.CreateModel(
            name='OutletExtraService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступность')),
            ],
            options={
                'verbose_name': 'Настройки дополнительной услуги для торговой точки',
                'verbose_name_plural': 'Настройки дополнительных услуг для торговых точек',
            },
        ),
        migrations.CreateModel(
            name='TerManBank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Приоритет банка')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terman_banks', to='banks.bank')),
            ],
            options={
                'verbose_name': 'Связь территориального менеджера с банком',
                'verbose_name_plural': 'Связи территориальных менеджеров с банками',
            },
        ),
        migrations.CreateModel(
            name='TerManExtraService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступность')),
                ('commission_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Комиссия. От')),
                ('commission_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Комиссия. До')),
                ('extra_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terman_extra_services', to='banks.extraservice')),
                ('terman_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terman_extra_services', to='banks.termanbank')),
            ],
            options={
                'verbose_name': 'Допустимая комиссия за доп. услугу по агенту',
            },
        ),
        migrations.CreateModel(
            name='TerManCreditProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступность')),
                ('commission_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Комиссия. От')),
                ('commission_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Комиссия. До')),
                ('credit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terman_credit_products', to='banks.creditproduct')),
                ('terman_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terman_credit_products', to='banks.termanbank')),
            ],
            options={
                'verbose_name': 'Допустимая комиссия за кредитный продукт по агенту',
            },
        ),
    ]
