# Generated by Django 3.2.6 on 2021-12-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_auto_20211217_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termancreditproduct',
            options={'verbose_name': 'Настройки и комиссия за кредитный продукт для территориала'},
        ),
        migrations.AlterModelOptions(
            name='termanextraservice',
            options={'verbose_name': 'Настройки и комиссия за доп. услугу для территориала'},
        ),
    ]
