# Generated by Django 3.2.6 on 2021-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdekToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cdek_uuid', models.UUIDField(null=True, verbose_name='Номер заказа СДЭК')),
                ('location', models.CharField(choices=[('in_outlet', 'На точке'), ('in_office', 'В офисе'), ('in_post', 'На почте'), ('in_bank', 'В банке')], default='in_outlet', max_length=9, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
