# Generated by Django 3.2.6 on 2021-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=1000, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('sender', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Отправитель')),
                ('receiver', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Получатель')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Сырые данные')),
                ('source', models.CharField(choices=[('auth-code', 'Отправка проверочного кода'), ('notification', 'Уведомление'), ('message', 'Сообщение')], default='notification', max_length=20, verbose_name='Тип отправки')),
                ('type', models.CharField(choices=[('sms', 'SMS-сообщение'), ('email', 'Email-сообщение'), ('push', 'Push-сообщение'), ('voice-message', 'Аудио-сообщение'), ('dialing', 'Дозвон'), ('telegram', 'Сообщение в Telegram')], default='sms', max_length=20, verbose_name='Тип сообщения')),
                ('status', models.CharField(choices=[('no-sent', 'Не отправлено'), ('sent', 'Отправлено'), ('received', 'Получено'), ('error', 'Ошибка')], default='sent', max_length=20, verbose_name='Status')),
                ('uuid', models.CharField(blank=True, max_length=200, null=True, verbose_name='UUID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения')),
            ],
        ),
    ]
