<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://siebel.com/CustomUI"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsdLocal1="http://www.siebel.com/xml/ATC%20Broker%20Update%20Application%20MQ%20Request"
	xmlns:xsdLocal2="http://www.siebel.com/xml/ApplicationInfoMQ"
	name="UpdateApplication"
	targetNamespace="http://siebel.com/CustomUI">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import
				namespace="http://www.siebel.com/xml/ATC%20Broker%20Update%20Application%20MQ%20Request"
				schemaLocation="UpdateApplicationMQRequest.xsd">
			</xsd:import>
			<xsd:import
				namespace="http://www.siebel.com/xml/ApplicationInfoMQ"
				schemaLocation="ApplicationInfoMQ.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="UpdateApplication_Input">
		<wsdl:part
			element="xsdLocal1:UpdateApplicationMQRequest"
			name="UpdateApplication_Input" />
	</wsdl:message>
	<wsdl:message name="UpdateApplication_Output">
		<wsdl:part element="xsdLocal2:ApplicationInfoMQ"
			name="UpdateApplication_Output" />
	</wsdl:message>

	<wsdl:portType name="UpdateApplication">
		<wsdl:operation name="UpdateApplication">
			<wsdl:input message="tns:UpdateApplication_Input" />
			<wsdl:output message="tns:UpdateApplication_Output" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="UpdateApplicationSOAP"
		type="tns:UpdateApplication">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="UpdateApplication">
			<soap:operation
				soapAction="http://siebel.com/CustomUI/UpdateApplication" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="UpdateApplication">
		<wsdl:port binding="tns:UpdateApplicationSOAP"
			name="UpdateApplicationSOAP">
			<soap:address location="http://172.18.18.20/" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
